---
- name: Delete User
  hosts: all
  become: true

  tasks:
    - name: Remove System Users
      user:
        name: "{{ item }}"
        state: absent
        remove: yes
      loop:
        - adm
        - lp
        - sync
        - shutdown
        - halt
        - news
        - uucp
        - operator
        - games
        - gopher
        - nfsnobody
        - squid
        - mail
        - proxy
        - list
        - gnats
        - irc
        - backup
        - landscape
        - fwupd-refresh
        - usbmux
        - pollinate
        - lxd
        - uuidd
      ignore_errors: yes



##### ansible-playbook execute
# ansible-playbook isms-p/delete-user_default.yaml --limit localhost
