- name: Edit hosts file
  hosts: all
  become: true
  # gather_facts: false

  vars:
    hosts_file_path: "/etc/hosts"
    new_host_entry: "8.8.8.8 www.google.com"

  tasks:
    - name: Read hosts file
      shell: cat "{{ hosts_file_path }}"
      register: hosts_file_content
      tags:
        - view_hosts_file

    - name: Display hosts file content
      debug:
        msg: "{{ hosts_file_content.stdout }}"
      tags:
        - view_hosts_file

    - name: Check if line exists
      set_fact:
        line_exists: "{{ new_host_entry in hosts_file_content.stdout }}"
      tags:
        - check_hosts_line

    - name: Add entry to hosts file
      lineinfile:
        path: "{{ hosts_file_path }}"
        line: "{{ new_host_entry }}"
      when: not line_exists|default(false)
      tags:
        - add_hosts_entry

    - name: Change ownership and permissions of hosts file
      file:
        path: "{{ hosts_file_path }}"
        owner: root
        group: root
        mode: "400"
      tags:
        - change_hosts_permissions

    - name: Remove entry from hosts file
      replace:
        path: "{{ hosts_file_path }}"
        regexp: "{{ new_host_entry }}"
        state: absent
      when: line_exists|default(false)
      tags:
        - remove_hosts_entry



### ansible-playbook execute
# ansible-playbook isms-p/edit_hosts_file.yml --syntax-check  
# ansible-playbook isms-p/edit_hosts_file.yml
# ansible-playbook isms-p/edit_hosts_file.yml --tags "add_hosts_entry" --limit node3

