- name: Edit hosts file
  hosts: all
  become: true

  vars:
    hosts_file_path: "/etc/hosts"
    new_host_entry: "8.8.8.8 www.google.com"

  tasks:
    - name: Read hosts file
      shell: cat /etc/hosts
      register: hosts_file_content
      tags: view_hosts_file

    - name: Display hosts file content
      debug:
        var: hosts_file_content.stdout
      tags: view_hosts_file

    - name: Add entry to hosts file
      block:
        - lineinfile:
            path: "{{ hosts_file_path }}"
            line: "{{ new_host_entry }}"
          tags:
            - add_hosts_entry

    - name: Change ownership and permissions of hosts file
      block:
        - file:
            path: "{{ hosts_file_path }}"
            owner: root
            group: root
            mode: "400"
          tags:
            - change_hosts_permissions

    - name: Remove entry from hosts file
      block:
        - replace:
            path: "{{ hosts_file_path }}"
            regexp: "{{ new_host_entry }}"
            state: absent
          tags:
            - remove_hosts_entry


### ansible-playbook execute
# ansible-playbook isms-p/edit_hosts_file.yml --syntax-check  
# ansible-playbook isms-p/edit_hosts_file.yml
# ansible-playbook isms-p/edit_hosts_file.yml --tags "add_hosts_entry" --limit node3

