###[U-69]로그온 시 경고 메시지 제공
---
- name: Set up warning message for authorized users
  hosts: all
  become: true

  tasks:
    - name: Set up /etc/issue.net
      copy:
        dest: /etc/issue.net
        content: |
          Warnning!!
          This system is for the use of authorized users only.

    - name: Create symlink from /etc/motd to /etc/issue.net
      file:
        src: /etc/issue.net
        dest: /etc/motd
        state: link
        force: yes