###[U-08]/etc/shadow 파일 소유자 및 권한 설정
---
- name: Set ownership and permissions for /etc/shadow
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Set ownership and permissions for /etc/shadow
      file:
        path: /etc/shadow
        owner: root
        group: root
        mode: '0400'
