---
- name: ICMP ping 테스트
  hosts: all
  gather_facts: false

  vars:
    icmp_test_ip: 8.8.8.8

  tasks:
    - name: "{{ icmp_test_ip }}로 ICMP ping 테스트 수행"
      shell: ping -c 3 -W 3 {{ icmp_test_ip }}
      register: result_ping
      ignore_errors: true

    - name: "{{ icmp_test_ip }}로 접근 가능한지 확인"
      set_fact:
        available: "{{ result_ping.rc == 0 }}"

    - debug:
        msg: "Host {{ inventory_hostname }} is {{ 'reachable' if available else 'unreachable' }}"


### Ansible
# ansible -i ./inventory localhost -m shell -a "ping -c3 -W3 8.8.8.8"

##### Ansible Playbook Execute
# ansible-playbook -i inventory/hosts.ini check-icmp-ping.yaml --limit localhost
#
# ansible-playbook -i inventory/hosts.ini check-icmp-ping.yaml -e icmp_test_ip=1.1.1.1 --limit localhost
