---
- name: ICMP Ping Test
  hosts: all

  vars:
    google_ping: 9.9.9.9

  tasks:
    - name: ICMP ping 테스트 수행
      shell: ping -c 3 -W 3 {{ google_ping }}
      register: result_ping
      ignore_errors: true

    - name: 호스트에 접근 가능한지 확인
      set_fact:
        available: "{{ result_ping.rc == 0 }}"

    - debug:
        msg: "Host {{ inventory_hostname }} is {{ 'reachable' if available else 'unreachable' }}"


##### ansible
# ansible -i ./inventory localhost -m shell -a "ping -c3 -W3 8.8.8.8"

##### ansible-playbook execute
# ansible-playbook -i inventory/hosts.ini check-icmp-ping.yaml --limit localhost
