- name: Check OS version
  hosts: all
  become: true

  tasks:
    - name: Show /etc/redhat-release on RHEL
      when: ansible_distribution == "RedHat"
      block:
        - name: Display /etc/redhat-release
          command:
            cmd: cat /etc/redhat-release
          register: var_redhat

        - name: Debug RHEL version
          debug:
            var: var_redhat.stdout_lines

    - name: Show /etc/lsb-release on Ubuntu
      when: ansible_distribution == "Ubuntu"
      block:
        - name: Display /etc/lsb-release
          command:
            cmd: cat /etc/lsb-release
          register: var_ubuntu

        - name: Debug Ubuntu version
          debug:
            var: var_ubuntu.stdout_lines


##### ansible-playbook execute
# ansible-playbook -i inventory.ini check-os_version.yaml --limit localhost
