---
- name: Add MySQL Hosts to Hosts File
  hosts: all
  become: true

  tasks:
    - name: Backup original hosts file
      command: cp /etc/hosts /etc/hosts.bak
      changed_when: false
      ignore_errors: true

    - name: Append MySQL Hosts to hosts file
      blockinfile:
        path: /etc/hosts
        marker: "### MySQL Hosts BEGIN"
        block: |
          192.168.20.211 node1
          192.168.20.212 node2
          192.168.20.213 node3
          192.168.20.209 node4
      tags:
        - update_hosts_file

    - name: Check if the entry exists
      shell: cat /etc/hosts | grep "### MySQL Hosts BEGIN"
      register: entry_check
      changed_when: false
      failed_when: false
      tags:
        - update_hosts_file

    - name: Display hosts file content
      debug:
        msg: "{{ entry_check.stdout }}"
      when: entry_check.stdout != ""
      tags:
        - update_hosts_file

    - name: Rollback hosts file if changes were not applied
      command: cp /etc/hosts.bak /etc/hosts
      when: entry_check.stdout == ""
      changed_when: false
      ignore_errors: true
      tags:
        - update_hosts_file


##### ansible-playbook execute
# ansible-playbook -i inventory/hosts.ini hosts-add.yaml