---
- name: ICMP Ping Test for Network Range
  hosts: all

  vars:
    network_range: "192.168.10.0/24"  # Replace with your desired network range

  tasks:
    - name: Generate list of IP addresses to ping
      set_fact:
        ping_targets: "{{ network_range | ipaddr('host') }}"

    - name: Perform ICMP ping test for each IP address
      ping:
        data: "{{ item }}"
        count: 3
        interval: 1
        timeout: 3
      register: ping_results
      loop: "{{ ping_targets }}"

    - name: Display reachability results
      debug:
        msg: "Host {{ item }} is {{ 'reachable' if ping_results.results[item].ping is defined else 'unreachable' }}"
      loop: "{{ ping_targets }}"


### Ansible Playbook Execute
#
# ansible-playbook -i inventory/hosts.ini network_ping.yml --limit localhost,centos7,ubuntu2204
#
# ansible-playbook -i inventory/hosts.ini network_ping.yml -e network_range=192.168.10.0/24 --limit localhost,centos7,ubuntu2204
