---
- name: 네트워크 서브넷에 대한 ICMP Ping 테스트
  hosts: localhost
  gather_facts: false

  vars:
    subnet: "192.168.1.0/24"

  tasks:
    - name: 서브넷에 포함된 모든 IP 주소 얻기
      set_fact:
        network_targets: "{{ query('network_subnet', subnet) | list }}"
      register: subnet_info

    - name: 각 호스트에 대한 ICMP Ping 테스트 수행
      ping:
        data: "{{ item }}"
      loop: "{{ subnet_info.network_targets }}"
      register: ping_results
      ignore_errors: true

    - name: 각 호스트에 대한 도달 가능성 확인 및 표시
      debug:
        msg: "Host {{ item.item }} is {{ 'reachable' if item.rc == 0 else 'unreachable' }}"
      loop: "{{ ping_results.results }}"



### Ansible Playbook Execute
#
# ansible-playbook -i inventory/hosts.ini network_ping.yml --limit localhost,centos7,ubuntu2204
#
# ansible-playbook -i inventory/hosts.ini network_ping.yml -e network_range=192.168.10.0/24 --limit localhost,centos7,ubuntu2204
