---
- name: 네트워크 서브넷에 대한 ICMP Ping 테스트
  hosts: all
  # gather_facts: false

  vars:
    subnet: "192.168.1.0/24"

  tasks:
    - name: 서브넷에 포함된 모든 IP 주소 얻기
      set_fact:
        network_targets: "{{ subnet | ipaddr('host') }}"

    - name: 각 호스트에 대한 ICMP Ping 테스트 수행
      ping:
        data: "{{ item }}"
        count: 3
        interval: 1
        timeout: 3
      register: ping_results

    - name: 각 호스트에 대한 도달 가능성 확인 및 표시
      debug:
        msg: "Host {{ item }} is {{ 'reachable' if ping_results.results[item].ping is defined else 'unreachable' }}"
      loop: "{{ network_targets }}"



### Ansible Playbook Execute
#
# ansible-playbook -i inventory/hosts.ini network_ping.yml --limit localhost,centos7,ubuntu2204
#
# ansible-playbook -i inventory/hosts.ini network_ping.yml -e network_range=192.168.10.0/24 --limit localhost,centos7,ubuntu2204
