---
- name: setup 모듈을 사용하여 facts 수집
  hosts: all

  tasks:
    - name: Use setup module to collect facts
      setup:

    - name: Display gathered facts
      debug:
        msg: "ansible_hostname = {{ ansible_hostname }}"

    - name: Display gathered facts using ansible_facts
      debug:
        msg: "ansible_facts.hostname = {{ ansible_facts.hostname }}"


### Ansible Playbook Execute
#
# ansible-playbook -i inventory/hosts.ini setup_playbook.yml --limit centos7
#
