---
- name: setup 모듈을 사용하여 facts 수집
  hosts: all

  tasks:
    - name: Use setup module to collect facts
      setup:

    - name: 수집된 facts 표시
      debug:
        msg: "ansible_hostname = {{ ansible_hostname }}"

    - name: ansible_facts를 사용하여 수집된 facts 표시
      debug:
        msg: "ansible_facts.hostname = {{ ansible_facts.hostname }}"


### Ansible Playbook Execute
#
# ansible-playbook -i inventory/hosts.ini setup_playbook.yml --limit centos7
#
