- name: Change user password
  hosts: all
  become: true

  tasks:
    - name: 패스워드 변경
      user:
        name: "{{ USER_NAME }}"
        password: "{{ PASSWORD | password_hash('sha512') }}"


##### ansible-playbook
# ansible-playbook -i inventory.ini user_password_change.yml --extra-vars "USER_NAME=<사용자_이름> PASSWORD=<변경할_패스워드>"
