---
- name: 예제 플레이북
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Outer Block
      block:
        - name: Loop Block
          block:
            - name: Task inside Loop
              debug:
                msg: "Loop Item: {{ item }}"
          loop:
            - 1
            - 2
            - 3
          always:
            - name: Always inside Loop
              debug:
                msg: "This always runs inside the loop"
        - name: Another Task inside Outer Block
          debug:
            msg: "This runs outside the loop"
      rescue:
        - name: Rescue Block
          debug:
            msg: "This runs on rescue"
      always:
        - name: Always Block
          debug:
            msg: "This always runs"


### ansible-playbook execute
# ansible-playbook -i inventory/hosts.ini ansible_learn/example3.yml --limit localhost,centos7,ubuntu2204
