---
- name: 예제 플레이북
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: 외부 블록
      block:
        - name: Loop Block
          block:
            - name: Task inside Loop
              debug:
                msg: "Loop Item: {{ item }}"
          loop:
            - 1
            - 2
            - 3
          always:
            - name: Always inside Loop
              debug:
                msg: "이것은 항상 루프 내부에서 실행됩니다."
        - name: 외부 블록 안의 다른 작업
          debug:
            msg: "이것은 루프 외부에서 실행됩니다."
      rescue:
        - name: Rescue Block
          debug:
            msg: "이것은 구조에서 실행됩니다(rescue)"
      always:
        - name: Always Block
          debug:
            msg: "이것은 항상 실행됩니다."


### ansible-playbook execute
# ansible-playbook -i inventory/hosts.ini ansible_learn/example3.yml --limit localhost,centos7,ubuntu2204
