---
- name: 예제 플레이북
  hosts: all
  gather_facts: true

  tasks:
    - name: 명령 실행하고 결과 등록
      command: echo "Hello, World!"
      register: command_result

    - name: 등록된 결과 디버깅
      debug:
        var: command_result.stdout

    - name: 다른 명령 실행하고 결과 등록
      command: ls /tmp
      register: ls_result

    - name: 다른 결과 디버깅
      debug:
        var: ls_result.stdout_lines


###
# ansible-playbook -i inventory/hosts.ini ansible_learn/example1.yml --limit localhost
