---
- name: Example Playbook
  hosts: localhost
  gather_facts: false
  become: true

  tasks:
    - name: Outer Block
      block:
        - name: Loop Block - Task 1
          debug:
            msg: "Loop Item: {{ item }}"
          loop:
            - 1
            - 2
            - 3
        - name: Loop Block - Task 2
          debug:
            msg: "Another Task inside Loop"
      rescue:
        - name: Rescue Block
          debug:
            msg: "This runs on rescue"
      always:
        - name: Always Block
          debug:
            msg: "This always runs"


### ansible-playbook execute
# ansible-playbook -i inventory/hosts.ini ansible_learn/example3.yml --limit localhost,centos7,ubuntu2204
