- name: Change user password
  hosts: all
  become: true

  tasks:
    - name: 패스워드 변경
      user:
        name: "{{ user_name }}"
        password: "{{ user_password | password_hash('sha512') }}"


##### ansible-playbook execute
# ansible-playbook -i inventory.ini user_password_change.yml --extra-vars "user_name=<사용자_이름> user_password=<변경할_패스워드>"
