---
- name: Create user
  hosts: all
  become: true

  tasks:
    - name: sudoers.d 추가
      copy:
        content: |
          {{ user_name }} ALL=(ALL) NOPASSWD: ALL
        dest: "/etc/sudoers.d/{{ user_name }}"
        owner: root
        group: root
        mode: 0440
        validate: "/usr/sbin/visudo -c -f '%s'"


##### ansible-playbook execute
# ansible-playbook -i inventory.ini user_sudoer_add.yaml --extra-vars "user_name=<생성할_사용자_이름>"
