---
- name: Configure root's PS1
  hosts: all
  become: yes  # root 권한으로 실행합니다.

  tasks:
    - name: Add PS1 to root's .bashrc
      lineinfile:
        dest: /root/.bashrc
        line: 'export PS1="\[\e[32m\]\u@\h\[\e[m\]:\[\e[36m\]\w\[\e[m\]\$ "'
      become: yes
      become_user: root
      ignore_errors: yes  # 이미 PS1이 있는 경우에도 무시하도록 설정합니다.

    - name: Add PS1 to root's .bash_profile
      lineinfile:
        dest: /root/.bash_profile
        line: 'export PS1="\[\e[32m\]\u@\h\[\e[m\]:\[\e[36m\]\w\[\e[m\]\$ "'
      become: yes
      become_user: root
      ignore_errors: yes  # 이미 PS1이 있는 경우에도 무시하도록 설정합니다.

##### ansible-playbook execute
# ansible-playbook -i user_command/user-ps1.yaml --limit localhost
