---
- name: Delete User
  hosts: all
  become: true

  tasks:
    - name: 현재 시스템 사용자 목록 가져오기
      shell:
        cmd: "cat /etc/passwd | cut -d: -f1"
      register: current_users
      changed_when: false
      tags:
        - get_users

    - name: Display all users (for debugging)
      debug:
        var: current_users.stdout_lines
      tags:
        - get_users

    - name: Remove System Users
      user:
        name: "{{ item }}"
        state: absent
        remove: yes
      loop:
        - adm
        - lp
        - sync
        - shutdown
        - halt
        - news
        - uucp
        - operator
        - games
        - gopher
        - nfsnobody
        - squid
        - mail
        - proxy
        - list
        - gnats
        - irc
        - backup
        - landscape
        - fwupd-refresh
        - usbmux
        - pollinate
        - lxd
        - uuidd
        - voice
        - fax
        - floppy
        - tape
        - video
      ignore_errors: yes
      tags:
        - remove_unnecessary_users


### Ansible Playbook Execute
#
# ansible-playbook -i inventory/hosts.ini user-command/delete_users_default.yml --limit centos7,ubuntu22
