---
- name: Delete user
  hosts: all
  become: true

  vars:
    user_name: vagrant  # Change this to the user you want to delete

  tasks:
    - name: 사용자 삭제
      user:
        name: "{{ user_name }}"
        state: absent

    - name: sudoers.d 파일 삭제
      file:
        path: "/etc/sudoers.d/{{ user_name }}"
        state: absent

    - name: Remove user from sudoers file
      lineinfile:
        path: /etc/sudoers
        state: absent
        regexp: '^{{ user_name }}\s'


### ansible-playbook execute
# ansible-playbook -i inventory/hosts.ini user_command/user_delete.yml --extra-vars "user_name=<삭제할_사용자_이름>"
#
# ansible-playbook -i inventory/hosts.ini user_command/user_delete.yml --extra-vars "user_name=vagrant2" --limit centos7,ubuntu2204
#