---
- name: Create Linux User
  hosts: all
  become: true
  vars:
    user_name: mysql

  tasks:
    - name: Create Linux User
      user:
        name: "{{ user_name }}"
        shell: /bin/false
        createhome: yes
        home: "/usr/local/{{ user_name }}"
        state: present
      become: true

##### ansible-playbook execute
# ansible-playbook -i inventory/hosts.ini user_command/user-create_mysql.yaml --limit localhost
