---
- name: Configure root's PS1
  hosts: all
  become: true

  vars:
    user_name: vagrant

  tasks:
    - name: Add PS1 to root's .bashrc
      lineinfile:
        dest: /root/.bashrc
        line: 'export PS1="\[\033[01;32m\]\u\[\e[m\]\[\033[01;32m\]@\[\e[m\]\[\033[01;32m\]\h\[\e[m\]:\[\033[01;34m\]\W\[\e[m\]$ "'
        create: yes
      ignore_errors: yes
      tags:
        - ps1_root

    - name: Add PS1 to user's .bashrc (linux user)
      lineinfile:
        dest: "/home/{{ user_name }}/.bashrc"
        line: 'export PS1="\[\e[31m\]\u\[\e[m\]\[\e[37m\]@\[\e[m\]\[\e[33m\]\h\[\e[m\]:\[\033[01;36m\]\W\[\e[m\]$ "'
        create: yes
      ignore_errors: yes
      tags:
        - ps1_user1

    - name: Add PS1 to user's .bashrc (docker user)
      lineinfile:
        dest: "/home/{{ user_name }}/.bashrc"
        line: 'export PS1="\[\e[33m\]\u\[\e[m\]\[\e[37m\]@\[\e[m\]\[\e[34m\]\h\[\e[m\]:\[\033[01;31m\]\W\[\e[m\]$ "'
        create: yes
      ignore_errors: yes
      tags:
        - ps1_user2


##### Ansible Playbook Execute
#
# ansible-playbook -i inventory/hosts.ini user_command/user_ps1.yml --limit localhost
#
# ansible-playbook -i inventory/hosts.ini user_command/user_ps1.yml --limit centos7,ubuntu2204 --tags ps1_root,ps1_user1
#
# ansible-playbook -i inventory/hosts.ini user-command/user_ps1.yml --limit localhost --tags ps1_root,ps1_user1
#