---
- name: Create Linux User
  hosts: all
  become: true
  
  vars:
    USER_NAME: mysql
    UID: 121
    GID: 121

  tasks:
    - name: Create Linux Group
      group:
        name: "{{ USER_NAME }}"
        GID: "{{ GID }}"
        state: present
      become: true

    - name: Create Linux User
      user:
        name: "{{ USER_NAME }}"
        UID: "{{ UID }}"
        group: "{{ USER_NAME }}"
        shell: /bin/false
        create_home: yes
        home: "/usr/local/{{ USER_NAME }}"
        state: present
      become: true
