---
- name: Create Linux User
  hosts: all
  become: true
  vars:
    username: mysql
    uid: 121
    gid: 121

  tasks:
    - name: Create Linux Group
      group:
        name: "{{ username }}"
        gid: "{{ gid }}"
        state: present
      become: true

    - name: Create Linux User
      user:
        name: "{{ username }}"
        uid: "{{ uid }}"
        group: "{{ username }}"
        shell: /bin/false
        create_home: yes
        home: "/usr/local/{{ username }}"
        state: present
      become: true
