---
- name: Deploy and extract MySQL archive
  hosts: all
  become: true
  gather_facts: false

  vars:
    mysql_archive: "mysql-8.0.34-linux-glibc2.28-x86_64.tar.gz"
    mysql_extract_dir: "/usr/local/mysql"
    mysql_install_dir: "/usr/local/mysql"

  tasks:
    - name: Copy MySQL archive to the target host
      copy:
        src: "/home/vagrant/ansible-cli/files/{{ mysql_archive }}"
        dest: "/tmp/{{ mysql_archive }}"
        remote_src: yes
      tags:
        - package-deploy

    - name: Ensure the MySQL installation directory exists
      file:
        path: "{{ mysql_install_dir }}"
        state: directory
      tags:
        - deploy

    - name: Extract MySQL archive
      unarchive:
        src: "/tmp/{{ mysql_archive }}"
        dest: "{{ mysql_extract_dir }}"
        remote_src: yes
        extra_opts: "--strip-components=1"
      tags:
        - unarchive

    - name: Copy MySQL installation script to the remote host
      copy:
        src: "/home/vagrant/ansible-cli/mysql/mysql-install.sh"
        dest: "/tmp/mysql-install.sh"
        mode: "0755"
      tags:
        - deploy

    - name: Execute MySQL installation script
      shell: /tmp/mysql-install.sh
      args:
        executable: /bin/bash
      tags:
        - deploy





##### ansible-playbook execute
# ansible-playbook mysql/install-mysql.yaml --limit localhost
#
# ansible-playbook mysql/install-mysql.yaml --limit localhost --tags package-deploy 
# ansible-playbook mysql/install-mysql.yaml --limit localhost --tags unarchive,deploy
