---
- name: Install libncurses5 package
  hosts: all
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      become: true

    - name: Install libncurses5 package
      apt:
        name: libncurses5
        state: present
      become: true



##### ansible-playbook execute
# ansible-playbook -i inventory/hosts.ini mysql/install-package_libncurses5.yaml --limit localhost