---
- name: Create Shell User (mysql)
  hosts: all
  become: true
  
  vars:
    USER_NAME: mysql
    UID: 121
    GID: 121

  tasks:
    - name: Create MySQL Shell Group
      group:
        name: "{{ USER_NAME }}"
        gid: "{{ GID }}"
        state: present
      become: true

    - name: Create MySQL Shell User
      user:
        name: "{{ USER_NAME }}"
        uid: "{{ UID }}"
        group: "{{ USER_NAME }}"
        shell: /bin/false
        create_home: yes
        home: "/home/{{ USER_NAME }}"
        state: present
      become: true


##### ansible-playbook execute
# ansible-playbook -i inventory/hosts.ini mysql/user-create_mysql.yaml --limit localhost
