---
- name: Install kubeadm, kubelet, kubectl
  hosts: all
  become: yes
  gather_facts: true

  tasks:
    - name: "Kubernetes 패키지 설치"
      apt:
        name:
          - kubeadm
          - kubelet
          - kubectl
        state: present
        update_cache: yes

    - name: "kubelet 서비스 시작 및 활성화"
      service:
        name: kubelet
        state: started
        enabled: yes

    - name: Check kubeadm version
      command: kubeadm version
      register: kubeadm_version

    - name: Check kubelet version
      command: kubelet --version
      register: kubelet_version

    - name: Check kubectl version
      command: kubectl version --short --client
      register: kubectl_version

    - name: Display kubeadm version
      debug:
        msg: "{{ kubeadm_version.stdout }}"

    - name: Display kubelet version
      debug:
        msg: "{{ kubelet_version.stdout }}"

    - name: Display kubectl version
      debug:
        msg: "{{ kubectl_version.stdout }}"



### Ansible
# ansible -i inventory/hosts.ini localhost -m shell -a "ping -c3 -W3 8.8.8.8"
#
### Ansible Playbook Execute
# ansible-playbook -i inventory/hosts.ini install-package/install_kubernetes.yml --limit localhost,k_group
#
# ansible-playbook -i inventory/hosts.ini install-package/install_kubernetes.yml --limit localhost,k_group