---
- name: Nginx 설치 및 구성
  hosts: all
  become: yes
  gather_facts: true

  tasks:
    - name: 필수 패키지 설치
      package:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - gnupg2
        - ca-certificates
        - lsb-release
        - ubuntu-keyring
      tags:
        - nginx_setup

    - name: Nginx 서명 키 가져오기 및 확인
      block:
        - name: 키 가져오기
          apt_key:
            url: https://nginx.org/keys/nginx_signing.key
            keyring: /usr/share/keyrings/nginx-archive-keyring.gpg
        - name: 키 확인
          apt_key:
            key: /usr/share/keyrings/nginx-archive-keyring.gpg
            check_signature: yes
      tags:
        - nginx_setup

    - name: Nginx 저장소 설정
      apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] http://nginx.org/packages/ubuntu {{ ansible_lsb.codename }} nginx
        state: present
      tags:
        - nginx_setup

    - name: 저장소 우선순위 설정
      copy:
        content: |
          Package: *
          Pin: origin nginx.org
          Pin: release o=nginx
          Pin-Priority: 900
        dest: /etc/apt/preferences.d/99nginx
      tags:
        - nginx_setup

    - name: 패키지 목록 업데이트 및 Nginx 설치
      block:
        - name: 패키지 목록 업데이트
          apt:
            update_cache: yes
          tags:
            - nginx_setup
            - nginx_install
        - name: Nginx 설치
          apt:
            name: nginx
            state: present
          tags:
            - nginx_install



###
# ansible-inventory -i inventory/hosts.ini --graph
#
# ansible-playbook -i inventory/hosts.ini check-icmp-ping.yml --limit ubuntu22
# 
# ansible-playbook -i inventory/hosts.ini install-package/install_nginx_on_ubuntu.yml --limit ubuntu22,centos7
