---
- name: 소스에서 Nginx 설치
  hosts: all
  become: yes
  gather_facts: true

  tasks:
    - name: Install prerequisites
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - build-essential
        - libpcre3
        - libpcre3-dev
        - zlib1g
        - zlib1g-dev
        - libssl-dev
        - libgd-dev
        - libxml2
        - libxml2-dev
        - uuid-dev
      tags:
        - nginx_setup

    - name: Download Nginx source tarball
      get_url:
        url: "https://nginx.org/download/nginx-1.24.0.tar.gz"
        dest: "/tmp/nginx-1.24.0.tar.gz"
      tags:
        - nginx_setup

    - name: Extract Nginx source tarball
      unarchive:
        src: "/tmp/nginx-1.24.0.tar.gz"
        dest: "/tmp"
        remote_src: yes
      tags:
        - nginx_setup

    - name: Configure Nginx
      command: >
        ./configure
        --prefix=/usr/share/nginx
        --conf-path=/etc/nginx/nginx.conf
        --http-log-path=/var/log/nginx/access.log
        --error-log-path=/var/log/nginx/error.log
        --lock-path=/var/lock/nginx.lock
        --pid-path=/run/nginx.pid
        --modules-path=/usr/lib/nginx/modules
        --with-compat
        --with-debug
        --with-pcre-jit
        --with-http_ssl_module
        --with-http_stub_status_module
        --with-http_realip_module
        --with-http_auth_request_module
        --with-http_v2_module
        --with-http_dav_module
        --with-http_slice_module
        --with-threads
        --with-http_addition_module
        --with-http_gunzip_module
        --with-http_gzip_static_module
        --with-http_sub_module
      args:
        chdir: "/tmp/nginx-1.24.0"
      tags:
        - nginx_setup

    - name: Compile Nginx
      command: >
        make -j$(nproc) 
      args:
        chdir: "/tmp/nginx-1.24.0"
      tags:
        - nginx_compile

    - name: Install Nginx
      make:
        chdir: "/tmp/nginx-1.24.0"
        target: install
      tags:
        - nginx_install

    - name: Create systemd service file for Nginx
      copy:
        src: "nginx.service"
        dest: "/lib/systemd/system/nginx.service"
      tags:
        - nginx_setup


###
# ansible-inventory -i inventory/hosts.ini --graph
#
# ansible-playbook -i inventory/hosts.ini check-icmp-ping.yml --limit ubuntu22
# 
# ansible-playbook -i inventory/hosts.ini install-package/install_nginx_sourcecode.yml --limit ubuntu22,centos7
