---
- name: Set editor to /usr/bin/vim.basic on Ubuntu
  hosts: all
  become: true

  tasks:
    # - name: Install vim.basic
    #   ansible.builtin.package:
    #     name: vim
    #     state: present
    #   when: ansible_distribution == 'Ubuntu'

    - name: Set editor using update-alternatives
      ansible.builtin.command:
        cmd: sudo update-alternatives --set editor /usr/bin/vim.basic
      when: ansible_distribution == 'Ubuntu'


### ansible-playbook execute
# ansible-playbook -i inventory/hosts.ini set-service/set_editor.yml --limit centos7,ubuntu2204
