---
- name: Set editor to /usr/bin/vim.basic on Ubuntu
  hosts: all
  become: true

  tasks:
    - name: Set editor using update-alternatives
      ansible.builtin.command:
        cmd: update-alternatives --set editor /usr/bin/vim.basic
      when: ansible_distribution == 'Ubuntu'

    - name: Get current editor using update-alternatives
      ansible.builtin.command:
        cmd: update-alternatives --display editor
      become: true
      when: ansible_distribution == 'Ubuntu'
      register: editor_result

    - debug:
        # var: editor_result.stdout_lines
        msg: "{{ editor_result.stdout_lines[2] }}"
      when: ansible_distribution == 'Ubuntu'


### ansible-playbook execute
# ansible-playbook -i inventory/hosts.ini set-service/set_editor.yml --limit centos7,ubuntu2204
