---
- name: mysql 셸 사용자 만들기
  hosts: all
  become: true
  
  vars:
    USER_NAME: mysql
    UID: 121
    GID: 121

  tasks:
    - name: Create MySQL Shell Group
      group:
        name: "{{ USER_NAME }}"
        gid: "{{ GID }}"
        state: present

    - name: Create MySQL Shell User
      user:
        name: "{{ USER_NAME }}"
        uid: "{{ UID }}"
        group: "{{ USER_NAME }}"
        shell: /bin/false
        home: "/home/{{ USER_NAME }}"
        state: present
        comment: "{{ USER_NAME }}"
      register: user_creation_result

    - name: Display Created User Information
      debug:
        var: user_creation_result.user


##### ansible-playbook execute
# ansible-playbook -i inventory/hosts.ini install-package/mysql/create_account_mysql --limit centos7,ubuntu2204
