---
- name: MySQL 압축 파일 배포 및 MySQL 설치
  hosts: all
  become: true
  # gather_facts: false

  vars:
    download_mysql_tarball: false
    mysql_archive: "mysql-8.0.34-linux-glibc2.28-x86_64.tar.gz"
    mysql_install_dir: "/usr/local/mysql"
    mysql_data_dir: "/usr/local/mysql/data"

  tasks:
    - name: MySQL 아카이브 복사(다운로드)
      copy:
        src: "{{ playbook_dir }}/../sourcedir/mysql/{{ mysql_archive }}"
        dest: "/tmp/{{ mysql_archive }}"
      when: download_mysql_tarball
      tags:
        - package_deploy

    - name: MySQL 홈페이지에서 MySQL 아키이브 다운로드
      shell: "wget https://dev.mysql.com/get/Downloads/MySQL-8.0/{{ mysql_archive }} -O /tmp/{{ mysql_archive }} > /dev/null 2>&1"
      when: not download_mysql_tarball
      tags:
        - package_deploy

    - name: MySQL 설치 디렉터리가 있는지 확인
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - "{{ mysql_install_dir }}"
        - "{{ mysql_data_dir }}"
      tags:
        - mysql_install

    - name: MySQL 아카이브 파일 압축 해제
      unarchive:
        src: "/tmp/{{ mysql_archive }}"
        dest: "{{ mysql_install_dir }}"
        remote_src: yes
        extra_opts: "--strip-components=1"
      tags:
        - mysql_install

    - name: MySQL 설치 디렉터리의 소유권 설정
      file:
        path: "{{ item }}"
        state: directory
        owner: mysql
        group: mysql
        mode: '0755'
      loop:
        - "{{ mysql_install_dir }}"
        - "{{ mysql_data_dir }}"
      tags:
        - mysql_install

    - name: "{{ mysql_install_dir }} 디렉터리의 소유권 설정"
      file:
        path: "{{ mysql_install_dir }}"
        state: directory
        recurse: yes
        owner: mysql
        group: mysql
      tags:
        - mysql_install

    - name: my.cnf 파일 만들기
      template:
        src: "{{ playbook_dir }}/../sourcedir/mysql/my.cnf.j2"
        dest: /etc/my.cnf
      tags:
        - mysql_install

    - name: "{{ mysql_archive }} 아카이브 파일 삭제"
      file:
        path: "/tmp/{{ mysql_archive }}"
        state: absent
      tags:
        - package_deploy_remove


##### ansible-playbook execute
# ansible-playbook -i inventory/hosts.ini install-package/mysql/install_mysql.yml --limit centos7,ubuntu2204
#
# ansible-playbook -i inventory/hosts.ini install-package/mysql/install_mysql.yml --limit centos7,ubuntu2204 --tags package_deploy 
# ansible-playbook -i inventory/hosts.ini install-package/mysql/install_mysql.yml --limit centos7,ubuntu2204 --tags mysql_install
# ansible-playbook -i inventory/hosts.ini install-package/mysql/install_mysql.yml --limit centos7,ubuntu2204 --tags package_deploy_remove
