---
- name: Deploy and extract MySQL archive
  hosts: all
  become: true
  gather_facts: false

  vars:
    download_mysql_tarball: false
    mysql_archive: "mysql-8.0.34-linux-glibc2.28-x86_64.tar.gz"
    mysql_extract_dir: "/usr/local/mysql"
    mysql_install_dir: "/usr/local/mysql"
    mysql_data_dir: "/usr/local/mysql/data"

  tasks:
    - name: MySQL 아카이브를 원격 호스트에 복사하기
      copy:
        src: "{{ playbook_dir }}/sourcedir/mysql/{{ mysql_archive }}"
        dest: "/tmp/{{ mysql_archive }}"
      tags:
        - package_deploy

    - name: Download MySQL tarball
      get_url:
        url: "https://dev.mysql.com/get/Downloads/MySQL-8.0/{{ mysql_archive }}"
        dest: "/tmp/{{ mysql_archive }}"
        mode: '0644'
      tags:
        - package_deploy
      when: download_mysql_tarball

    - name: MySQL 설치 디렉터리가 있는지 확인
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - "{{ mysql_install_dir }}"
        - "{{ mysql_data_dir }}"
      tags:
        mysql_directory_create

    - name: MySQL 아카이브 압축 해제
      unarchive:
        src: "/tmp/{{ mysql_archive }}"
        dest: "{{ mysql_extract_dir }}"
        remote_src: yes
        extra_opts: "--strip-components=1"
      tags:
        - mysql_unarchive

    - name: MySQL 설치 디렉터리의 소유권 설정
      file:
        path: "{{ item }}"
        state: directory
        owner: mysql
        group: mysql
        mode: '0755'
      loop:
        - "{{ mysql_install_dir }}"
        - "{{ mysql_data_dir }}"
      tags:
        - mysql_directory_create

    - name: my.cnf 파일 만들기
      template:
        src: "{{ playbook_dir }}/sourcedir/mysql/my.cnf.j2"
        dest: /etc/my.cnf
      tags:
        - mysql_cnf_create


##### ansible-playbook execute
# ansible-playbook -i inventory/hosts.ini mysql/install-mysql.yaml --limit localhost
#
# ansible-playbook -i inventory/hosts.ini mysql/install-mysql.yaml --limit localhost --tags package-deploy 
# ansible-playbook -i inventory/hosts.ini mysql/install-mysql.yaml --limit localhost --tags unarchive,deploy
