---
- name: Deploy and extract MySQL archive
  hosts: all
  become: true
  gather_facts: false

  vars:
    mysql_archive: "mysql-8.0.34-linux-glibc2.28-x86_64.tar.gz"
    mysql_extract_dir: "/usr/local/mysql"
    mysql_install_dir: "/usr/local/mysql"
    mysql_data_dir: "/usr/local/mysql/data"

  tasks:
    - name: Copy MySQL archive to the remote host
      copy:
        src: "{{ playbook_dir }}/sourcedir/mysql/{{ mysql_archive }}"
        dest: "/tmp/{{ mysql_archive }}"
      tags:
        - package-deploy

    # - name: Download MySQL tarball
    #   ansible.builtin.get_url:
    #     url: "https://dev.mysql.com/get/Downloads/MySQL-8.0/{{ mysql_archive }}"
    #     dest: "/tmp/{{ mysql_archive }}"
    #     mode: '0644'
    #   tags:
    #     - package-deploy

    - name: MySQL 설치 디렉터리가 있는지 확인
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - "{{ mysql_install_dir }}"
        - "{{ mysql_data_dir }}"
      tags:
        mysql_deploy

    - name: Extract MySQL archive
      unarchive:
        src: "/tmp/{{ mysql_archive }}"
        dest: "{{ mysql_extract_dir }}"
        remote_src: yes
        extra_opts: "--strip-components=1"
      tags:
        - mysql_unarchive

    - name: MySQL 설치 디렉터리의 소유권 설정
      file:
        path: "{{ item }}"
        state: directory
        owner: mysql
        group: mysql
        mode: '0755'
      loop:
        - "{{ mysql_install_dir }}"
        - "{{ mysql_data_dir }}"
      tags:
        - mysql_unarchive

    - name: Create my.cnf file
      template:
        src: "{{ playbook_dir }}/sourcedir/mysql/my.cnf.j2"
        dest: /etc/my.cnf
      tags:
        - mysql_unarchive


##### ansible-playbook execute
# ansible-playbook -i inventory/hosts.ini mysql/install-mysql.yaml --limit localhost
#
# ansible-playbook -i inventory/hosts.ini mysql/install-mysql.yaml --limit localhost --tags package-deploy 
# ansible-playbook -i inventory/hosts.ini mysql/install-mysql.yaml --limit localhost --tags unarchive,deploy
