---
- name: MySQL 압축 파일 배포 및 계정 생성 및 MySQL 설치
  hosts: all
  become: true

  vars:
    download_mysql_tarball: true
    mysql_archive: "mysql-8.0.34-linux-glibc2.28-x86_64.tar.gz"
    mysql_install_dir: "/usr/local/mysql"
    mysql_data_dir: "{{ mysql_install_dir }}/data"

  tasks:
    - include_tasks: create_account_mysql.yml
    - include_tasks: install_mysql.yml


##### ansible-playbook execute
# ansible-playbook -i inventory/hosts.ini install-package/mysql/main.yml --limit centos7,ubuntu2204
#
# ansible-playbook -i inventory/hosts.ini install-package/mysql/main.yml --limit centos7,ubuntu2204 --tags package_deploy 
# ansible-playbook -i inventory/hosts.ini install-package/mysql/main.yml --limit centos7,ubuntu2204 --tags mysql_install
# ansible-playbook -i inventory/hosts.ini install-package/mysql/main.yml --limit centos7,ubuntu2204 --tags package_deploy_remove
