---
- name: Check OS version
  hosts: all
  become: true

  tasks:
    - name: Show distribution information
      block:
        - name: Display /etc/redhat-release on CentOS
          ansible.builtin.shell:
            cmd: cat /etc/redhat-release
          when: ansible_distribution == "CentOS"
          register: redhat_release

        - name: Display /etc/lsb-release on Ubuntu
          ansible.builtin.shell:
            cmd: cat /etc/lsb-release
          when: ansible_distribution == "Ubuntu"
          register: ubuntu_release

        - name: Debug distribution information on CentOS
          ansible.builtin.debug:
            var: redhat_release.stdout_lines
          when: ansible_distribution == "CentOS"

        - name: Debug distribution information on Ubuntu
          ansible.builtin.debug:
            var: ubuntu_release.stdout_lines
          when: ansible_distribution == "Ubuntu"

      rescue:
        - name: Display unknown distribution message
          ansible.builtin.debug:
            msg: "Unknown distribution"

      always:
        - name: Display ansible_distribution fact
          ansible.builtin.debug:
            var: ansible_distribution


### ansible-playbook execute
# ansible-playbook -i inventory/hosts.ini linux-configure-check/check_os_version.yml --limit localhost,centos7,ubuntu2204
