---
- name: Display current time
  hosts: all
  become: true
  # gather_facts: false

  tasks:
    - name: Get current time
      shell: date
      register: current_time

    - name: Display current time
      debug:
        # var: current_time.stdout
        var: current_time.output



### ansible-playbook execute
# ansible-playbook -i inventory/hosts.ini linux-configure-check/current-time.yaml --limit localhost,centos7,ubuntu2204
