---
- name: /etc/fstab에서 스왑 사용 안 함
  hosts: all
  become: true

  tasks:
    - name: Turn off swap
      command: swapoff -a

    - name: /etc/fstab에서 스왑 항목을 주석 처리
      replace:
        path: /etc/fstab
        regexp: '^(\S+\s+)(\S+\s+swap\s+\S+\s+\S+\s*)(\S+\s*)'
        replace: '#\1\2\3'
      ignore_errors: yes

  handlers:
    - name: Reload fstab
      shell: mount -a
      ignore_errors: yes



### ansible-playbook execute
# ansible-playbook -i inventory/hosts.ini linux-setup/disable_swap.yml --limit localhost
