---
- name: 시스템 리소스 설정
  hosts: all
  become: yes

  tasks:
    - name: Set soft nofile limit
      sysctl:
        name: fs.file-max
        value: 65536
        state: present
      become_user: root

    - name: Set hard nofile limit
      sysctl:
        name: fs.file-max
        value: 65536
        state: present
        sysctl_set: yes
      become_user: root

    - name: Set soft memlock limit
      sysctl:
        name: vm.max_map_count
        value: 262144
        state: present
      become_user: root

    - name: Set hard memlock limit
      sysctl:
        name: vm.max_map_count
        value: 262144
        state: present
        sysctl_set: yes
      become_user: root



### ansible-playbook execute
# ansible-playbook -i inventory/hosts.ini linux-setup/set_limits.yml --limit localhost
