---
- name: 시스템 리소스 설정(/etc/security/limits.conf)
  hosts: all
  become: yes

  tasks:
    - name: Add soft nofile limit to limits.conf
      lineinfile:
        path: /etc/security/limits.conf
        line: '* soft nofile 65536'
      become_user: root

    - name: Add hard nofile limit to limits.conf
      lineinfile:
        path: /etc/security/limits.conf
        line: '* hard nofile 65536'
      become_user: root

    - name: Add soft memlock limit to limits.conf
      lineinfile:
        path: /etc/security/limits.conf
        line: '* soft memlock unlimited'
      become_user: root

    - name: Add hard memlock limit to limits.conf
      lineinfile:
        path: /etc/security/limits.conf
        line: '* hard memlock unlimited'
      become_user: root



### ansible-playbook execute
# ansible-playbook -i inventory/hosts.ini linux-setup/set_limits.yml --limit localhost
