---
- name: Set Timezone to Asia/Seoul
  hosts: all
  become: yes

  tasks:
    - name: Install systemd package (if not already installed)
      ansible.builtin.package:
        name: systemd
        state: present
      when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'CentOS'
      tags:
        - timezone_setup

    - name: Set timezone
      ansible.builtin.command:
        cmd: timedatectl set-timezone Asia/Seoul
      tags:
        - timezone_setup

    - name: Display current timezone
      ansible.builtin.command:
        cmd: timedatectl
      register: timezone_result
      tags:
        - timezone_check

    - debug:
        # var: timezone_result.stdout
        # var: timezone_result.stdout_lines[3]
        msg: "{{ timezone_result.stdout_lines[3] }}"
      tags:
        - timezone_check


### ansible-playbook execute
# ansible-playbook -i inventory/hosts.ini linux-setup/set_timezone.yml --limit centos7,ubuntu2204 --tags=timezone_setup
# ansible-playbook -i inventory/hosts.ini linux-setup/set_timezone.yml --limit centos7,ubuntu2204 --tags=timezone_check
#
# ansible-playbook -i inventory/hosts.ini linux-setup/set_timezone.yml --limit centos7,ubuntu2204
