- name: 부팅 시 실행할 스크립트 설정
  hosts: all
  become: yes

  tasks:
    - name: rc.local 서비스 활성화 (Ubuntu)
      systemd:
        name: rc-local
        enabled: yes
      become_method: sudo
      when: ansible_distribution == 'Ubuntu'
      tags:
        - rc-local_enable

    - name: rc.local 서비스 시작 (Ubuntu)
      systemd:
        name: rc-local
        state: started
      become_method: sudo
      when: ansible_distribution == 'Ubuntu'
      tags:
        - rc-local_start

    - name: rc.local 스크립트 파일 생성 (Ubuntu)
      copy:
        content: |
          #!/bin/bash

          # 여기에 스크립트 내용을 작성하세요
        dest: /etc/rc.local
        mode: '0755'  # 실행 권한을 부여합니다.
      become_method: sudo
      when: ansible_distribution == 'Ubuntu'
      tags:
        - rc-local_create


### ansible-playbook execute
# ansible-playbook -i inventory/hosts.ini linux-setup/set_rc-local.yml

# systemctl restart rc-local
# systemctl status rc-local
