---
- name: CentOS 미러 업데이트
  hosts: all
  become: true

  tasks:
    - name: Backup CentOS-Base.repo file
      ansible.builtin.copy:
        src: /etc/yum.repos.d/CentOS-Base.repo
        dest: "/etc/yum.repos.d/CentOS-Base.repo.{{ ansible_date_time.date }}"
        remote_src: yes
      register: backup_result
      when: ansible_distribution == 'CentOS'

    - name: Comment out mirrorlist in CentOS-Base.repo
      ansible.builtin.replace:
        path: /etc/yum.repos.d/CentOS-Base.repo
        regexp: '^mirrorlist(.*)'
        replace: '#mirrorlist\1'
        backup: yes
      when: ansible_distribution == 'CentOS'

    - name: Replace baseurl in CentOS-Base.repo
      ansible.builtin.replace:
        path: /etc/yum.repos.d/CentOS-Base.repo
        regexp: '^#baseurl=http:\/\/mirror.centos.org'
        replace: 'baseurl=https:\/\/mirror.kakao.com'
        backup: yes
      when: ansible_distribution == 'CentOS'

    - name: Display backup result
      ansible.builtin.debug:
        var: backup_result
      when: ansible_distribution == 'CentOS'


### ansible-playbook execute
#
# ansible-playbook -i inventory/hosts.ini linux-setup/set_yum_repository.yml --limit centos7,ubuntu2204
